SELECT LIPS.LIPS_VBELN AS "NRO_OC",
			LIKP.LIKP_LDDAT AS "FECHA_CARGA",
			LIKP.LIKP_KUNAG AS "SOLIC",
			KNA1.KNA1_NAME1 AS "DESTINATARIO",
            LIPS.LIPS_MATNR AS "N_MATERIAL",
			--clase doc venta (filtro)
			MARA.MAKT_MAKTX AS "DENOM_MATERIAL",
			LIPS.LIPS_LFIMG AS "CANTIDAD",
			LIPS.LIPS_GEWEI AS "UM",
			CASE WHEN LIPS.LIPS_GEWEI = 'KG' THEN LIPS.LIPS_BRGEW
			/1000 ELSE LIPS.LIPS_BRGEW END AS "PESO_BRUTO",
			LIPS.LIPS_BRGEW AS "PES_BRUTO ORIGINAL",
			LIPS.LIPS_WERKS AS "CENTRO",
			LIPS.LIPS_POSNR AS "POSICION_OC",
			LIKP.LIKP_LFDAT AS "FECHA_ENTREGA",					
			LIKP.LIKP_ROUTE AS "RUTA"
			--VBUK.VBUK_VBTYP AS "DOC_ENTREGA"

FROM sap.TBL_ENTREGAS_SHP_IDX_GDSI GDSI
       INNER JOIN sap.TBL_ENTREGAS_MM_VBUK VBUK ON VBUK.VBUK_VBELN = GDSI.SHP_IDX_GDSI_VBELN
	   INNER JOIN sap.TBL_CLIENTES_KNA1 KNA1 ON KNA1.KNA1_KUNNR = GDSI.SHP_IDX_GDSI_KUNNR  --Clientes
       INNER JOIN sap.TBL_ENTREGAS_CABECERA_MM_LIKP LIKP ON LIKP.LIKP_VBELN = GDSI.SHP_IDX_GDSI_VBELN --OC cabecera
       INNER JOIN sap.TBL_ENTREGAS_POSICION_MM_LIPS LIPS ON LIPS.LIPS_VBELN = GDSI.SHP_IDX_GDSI_VBELN --OC posición
	   INNER JOIN sap.TBL_MATERIALES_MARA MARA ON MARA.MARA_MATNR = LIPS.LIPS_MATNR --Materiales
	   --INNER JOIN sap.TBL_PEDIDO_VENTA_VBBE VBBE ON VBBE.VBBE_VBELN = LIPS.LIPS_VGBEL -- ORDEN DE VENTA 
	   
WHERE  VBUK.VBUK_VBTYP = 'J' --
              AND VBUK.VBUK_WBSTK <> 'C' --
              AND VBUK.VBUK_BESTK IS NULL --
              AND LIPS.LIPS_UECHA = '000000'
			  AND LIPS.LIPS_WERKS = '7700'

				--HASTA ACA EL WHERE PARA LIMPIAR EL ID

			  AND LIPS.LIPS_VTWEG = '7D'	--CANAL
			  AND LIPS.LIPS_SPART = '7J'	--SECTOR
			  AND LIKP.LIKP_VKORG = '7103'  --ORG DE VENTAS
			  AND LIKP.LIKP_FKARV = 'Y7PI'  --CLASE DOC VENTAS
			  AND LIKP.LIKP_INCO1 = 'CIF'	--INCOTERM
			  AND LIKP.LIKP_BOLNR IS NULL	--CARTA DE PORTE
			  AND (CASE WHEN LIPS.LIPS_GEWEI = 'KG' THEN LIPS.LIPS_BRGEW/1000 ELSE LIPS.LIPS_BRGEW END)> 0.25
			  
ORDER BY RUTA DESC, SOLIC DESC, PESO_BRUTO DESC

